import os
import time
import hmac
import functools
from werkzeug.security import generate_password_hash, check_password_hash
from flask import session, redirect, url_for, request, jsonify
from core.utils import logger

# ── CONSTANTS ────────────────────────────────────────────────────────
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION   = 300   # 5 minutes in seconds
SESSION_LIFETIME   = 3600  # 1 hour in seconds

# In-memory brute-force tracker: { ip: { "attempts": int, "locked_until": float } }
_login_attempts: dict = {}

# ── HELPERS ──────────────────────────────────────────────────────────


def _get_client_ip() -> str:
    """Return real IP, respecting Railway's proxy headers."""
    return (
        request.headers.get("X-Forwarded-For", "").split(",")[0].strip()
        or request.remote_addr
        or "unknown"
    )


def _is_locked_out(ip: str) -> bool:
    """Return True if this IP is currently in lockout."""
    record = _login_attempts.get(ip)
    if not record:
        return False
    if record["locked_until"] and time.time() < record["locked_until"]:
        return True
    # Lockout expired — reset
    _login_attempts.pop(ip, None)
    return False


def _record_failed_attempt(ip: str):
    """Increment failure count; lock out after MAX_LOGIN_ATTEMPTS."""
    record = _login_attempts.setdefault(ip, {"attempts": 0, "locked_until": 0.0})
    record["attempts"] += 1
    if record["attempts"] >= MAX_LOGIN_ATTEMPTS:
        record["locked_until"] = time.time() + LOCKOUT_DURATION
        logger.warning(f"Admin login locked for IP {ip} after {MAX_LOGIN_ATTEMPTS} failed attempts.")


def _clear_attempts(ip: str):
    """Clear failure record on successful login."""
    _login_attempts.pop(ip, None)


def _is_safe_redirect(url: str) -> bool:
    """Prevent open-redirect attacks — only allow relative paths."""
    if not url:
        return False
    # Must start with / but not // (protocol-relative URLs)
    return url.startswith("/") and not url.startswith("//")


# ── PUBLIC API ───────────────────────────────────────────────────────

def check_credentials(username: str, password: str) -> bool:
    """
    Secure credential check:
    - Username: constant-time HMAC comparison (prevents timing attacks)
    - Password: werkzeug PBKDF2-HMAC-SHA256 hash verification

    ADMIN_PASSWORD in Railway vars should be a hashed value generated by:
        python -c "from werkzeug.security import generate_password_hash; print(generate_password_hash('yourpassword'))"

    Falls back to plaintext comparison if the stored value is not a hash,
    so existing deployments keep working — but logs a warning to upgrade.
    """
    expected_user = os.getenv("ADMIN_USERNAME", "")
    expected_pass = os.getenv("ADMIN_PASSWORD", "")

    if not expected_user or not expected_pass:
        logger.error("ADMIN_USERNAME or ADMIN_PASSWORD not set in environment.")
        return False

    # Constant-time username comparison
    user_ok = hmac.compare_digest(username.encode(), expected_user.encode())
    if not user_ok:
        return False

    # Password: prefer hashed comparison, fall back to plaintext with warning
    if expected_pass.startswith("pbkdf2:") or expected_pass.startswith("scrypt:"):
        # Stored as a proper werkzeug hash — use secure comparison
        return check_password_hash(expected_pass, password)
    else:
        # Plaintext fallback — still constant-time, but warn the operator
        logger.warning(
            "ADMIN_PASSWORD is stored as plaintext. "
            "Hash it with: python -c \"from werkzeug.security import generate_password_hash; "
            "print(generate_password_hash('yourpassword'))\" "
            "and update your Railway environment variable."
        )
        return hmac.compare_digest(password.encode(), expected_pass.encode())


def attempt_login(username: str, password: str) -> tuple[bool, str]:
    """
    Full login flow: rate-limit check → credential check → session setup.
    Returns (success: bool, error_message: str).
    """
    ip = _get_client_ip()

    if _is_locked_out(ip):
        remaining = int(_login_attempts[ip]["locked_until"] - time.time())
        logger.warning(f"Blocked login attempt from locked IP {ip}.")
        return False, f"Too many failed attempts. Try again in {remaining} seconds."

    if check_credentials(username, password):
        _clear_attempts(ip)
        session["admin_logged_in"] = True
        session["admin_login_time"] = time.time()
        session["admin_ip"] = ip
        session.permanent = False  # Session expires when browser closes
        logger.info(f"Admin login successful from IP {ip}.")
        return True, ""
    else:
        _record_failed_attempt(ip)
        attempts_left = MAX_LOGIN_ATTEMPTS - _login_attempts.get(ip, {}).get("attempts", 0)
        attempts_left = max(0, attempts_left)
        logger.warning(f"Failed admin login from IP {ip}. {attempts_left} attempts remaining.")
        return False, f"Invalid credentials. {attempts_left} attempts remaining before lockout."


def is_session_valid() -> bool:
    """Check admin session exists and hasn't expired."""
    if not session.get("admin_logged_in"):
        return False
    login_time = session.get("admin_login_time", 0)
    if time.time() - login_time > SESSION_LIFETIME:
        session.clear()
        logger.info("Admin session expired.")
        return False
    return True


def logout():
    """Clear admin session completely."""
    ip = session.get("admin_ip", "unknown")
    session.clear()
    logger.info(f"Admin logout from IP {ip}.")


def get_safe_redirect(fallback: str = "/admin") -> str:
    """Return a validated next-URL or the fallback."""
    next_url = request.args.get("next", "")
    return next_url if _is_safe_redirect(next_url) else fallback


# ── DECORATORS ───────────────────────────────────────────────────────

def login_required(f):
    """Protect admin page routes — redirects to login if not authenticated."""
    @functools.wraps(f)
    def decorated(*args, **kwargs):
        if not is_session_valid():
            return redirect(url_for("admin_login", next=request.path))
        return f(*args, **kwargs)
    return decorated


def api_login_required(f):
    """Protect admin API routes — returns 401 JSON instead of redirecting."""
    @functools.wraps(f)
    def decorated(*args, **kwargs):
        if not is_session_valid():
            return jsonify({"error": "Authentication required."}), 401
        return f(*args, **kwargs)
    return decorated
